package_description: 'Additional Check_MK checks'
package_website: 'https://github.com/tobru/check-mk-checks'
cmk_checks_dir: '/usr/share/check_mk/checks'
cmk_checksdoc_dir: '/usr/share/doc/check_mk/checks'
cmk_perfometer_dir: '/usr/share/check_mk/web/plugins/perfometer'
cmk_pnptemplates_dir: '/usr/share/pnp4nagios/html/templates'
omd_checks_dir: 'local/share/check_mk/checks'
omd_checksdoc_dir: 'local/share/check_mk/checkman'
omd_perfometer_dir: 'local/share/check_mk/web/plugins/perfometer'
omd_pnptemplates_dir: 'local/share/check_mk/pnp-templates'
