#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Author: Tobias Brunner <tobias.brunner@nine.ch>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Original decription from SNMP:
# 'Power supply 1 (NA - AC - Regular) present, status ok'
# -> Split at first (

def inventory_brocade_psu(info):
   inventory = []
   if len(info) > 0:
       for line in info:
           inventory.append( (line[0].split(' (')[0], None) )
       return inventory

def check_brocade_psu(item, _no_params, info):
   for name, value in info:
       if name.split(' (')[0] == item:
           if value == '3':
               return (2, "CRITICAL - PSU has status FAILURE")
           if value == '2':
               return (0, "OK - PSU has status NORMAL")
           if value == '1':
               return (0, "WARNING - PSU has status OTHER")
           else:
               return (3, "UNKNOWN - PSU status is unknown" + value)
   return (3, "UNKNOWN - PSU status is unknown")

check_info['brocade_psu'] = {
    "inventory_function"      : inventory_brocade_psu,
    "check_function"          : check_brocade_psu,
    "service_description"     : "PSU %s",
    "has_perfdata"            : False,
    "group"                   : "psu",
    "snmp_info"               : ( ".1.3.6.1.4.1.1991.1.1.1.2.1.1", [ "2", "3" ]),
    "snmp_scan_function"      : lambda oid: "brocade" in oid(".1.3.6.1.2.1.1.1.0").lower(),
}
