#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Author: Tobias Brunner <tobias.brunner@nine.ch>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

def inventory_brocade_fan(info):
   if len(info) > 0:
       return [ (line[0], None) for line in info ]

def check_brocade_fan(item, _no_params, info):
   for name, value in info:
       if name == item:
           if value == '3':
               return (2, "CRITICAL - FAN has status FAILURE")
           if value == '2':
               return (0, "OK - FAN has status NORMAL")
           if value == '1':
               return (0, "WARNING - FAN has status OTHER")
           else:
               return (3, "UNKNOWN - FAN status is unknown")
   return (3, "UNKNOWN - FAN status is unknown")

check_info['brocade_fan'] = {
    "inventory_function"      : inventory_brocade_fan,
    "check_function"          : check_brocade_fan,
    "service_description"     : "Fan %s",
    "has_perfdata"            : False,
    "group"                   : "fan",
    "snmp_info"               : ( ".1.3.6.1.4.1.1991.1.1.1.3.1.1", [ "2", "3" ]),
    "snmp_scan_function"      : lambda oid: "brocade" in oid(".1.3.6.1.2.1.1.1.0").lower(),
}
