#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Author: Tobias Brunner <tobias.brunner@nine.ch>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


brocade_cpu_default_levels = (80.0, 90.0)

def check_brocade_cpu(item, params, info):
    util = float(info[0][0]) 
    infotext = " - %2.1f%% utilization in last 5minutes" % util
    warn, crit = params
    perfdata = [("util", util, warn, crit, 0, 100)]
    if util >= crit:
        return (2, "CRIT" + infotext + " (critical at %d%%)" % crit, perfdata)
    elif util >= warn:
        return (1, "WARN" + infotext + " (warning at %d%%)" % warn, perfdata)
    else:
        return (0, "OK" + infotext, perfdata)

check_info["brocade_cpu"] = {
    "check_function"        : check_brocade_cpu,
    "inventory_function"    : lambda info: [(None, "brocade_cpu_default_levels")],
    "service_description"   : "CPU utilization",
    "has_perfdata"          : True,
    "group"                 : "cpu_utilization",
    "snmp_scan_function"    : lambda oid: "brocade" in oid(".1.3.6.1.2.1.1.1.0").lower(),
    "snmp_info"		    : ( ".1.3.6.1.4.1.1991.1.1.2.11.1.1.5.1.1", [ 300 ]),
}

